import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
<<<<<<< HEAD
import { ThemeProvider } from "next-themes";
=======
>>>>>>> ced9568 (Initial commit from Create Next App)
=======
import { ThemeProvider } from "next-themes";
>>>>>>> 0ed5cf9 (commit)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
<<<<<<< HEAD
  title: "Yatri's Portfolio",
  description: "Modern and Minimalist",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> ced9568 (Initial commit from Create Next App)
=======
  title: "Yatri's Portfolio",
  description: "Modern and Minimalist",
>>>>>>> 0ed5cf9 (commit)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 0ed5cf9 (commit)
        <ThemeProvider 
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
<<<<<<< HEAD
=======
        {children}
>>>>>>> ced9568 (Initial commit from Create Next App)
=======
>>>>>>> 0ed5cf9 (commit)
      </body>
    </html>
  );
}
